/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject1;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;

/**
 *
 * @author Efe
 */
public class AnalyseCodeAndOutput extends javax.swing.JFrame {
    static String projectName;
    static String assignmentName;

    public AnalyseCodeAndOutput() {
        initComponents();
    }
    
    public AnalyseCodeAndOutput(String projectName,String assignmentName) {
        initComponents();
        this.projectName = projectName;
        this.assignmentName = assignmentName;
        list.setListData(FileWriterA.reportList(projectName));
    }

    public static void seePath(String name) {
        // Dosya yolu ve dosya adı
        String working = System.getProperty("user.dir");
        String dosyaYolu =working+File.separator+"Projects"+File.separator+projectName+File.separator;
        String dosyaAdi = "deneme.c";

        // Dosya okuma ve yazma işlemleri
        try {
            // Okunacak dosyanın yolu
            String okunacakDosyaYolu = dosyaYolu + dosyaAdi;
            
            // Okunan dosyadan veri oku
            BufferedReader okuyucu = new BufferedReader(new FileReader(okunacakDosyaYolu));
            
            // Yazılacak dosyanın adı ve yolu
            String ciktiDosyaYolu = "C:\\path\\to\\cikti.txt";

            // Çıktı dosyasına veri yaz
            BufferedWriter yazici = new BufferedWriter(new FileWriter(ciktiDosyaYolu));
            String satir;
            while ((satir = okuyucu.readLine()) != null) {
                yazici.write(satir);
                yazici.newLine(); // Yeni satır ekle
            }

            // Dosyaları kapat
            okuyucu.close();
            yazici.close();

            System.out.println(dosyaAdi + " dosyasının içeriği başarıyla " + ciktiDosyaYolu + " dosyasına yazıldı.");
        } catch (IOException e) {
            System.out.println("Dosya işlemleri sırasında bir hata oluştu: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        list = new javax.swing.JList<>();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        list.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(list);

        jButton2.setText("Output");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        txtArea.setColumns(20);
        txtArea.setRows(5);
        jScrollPane2.setViewportView(txtArea);

        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Code");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 693, Short.MAX_VALUE)
                            .addComponent(jScrollPane2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(jButton2)
                        .addGap(232, 232, 232)
                        .addComponent(jButton4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton4))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String name = (String)list.getSelectedValue();
        txtArea.setText("");
        String working = System.getProperty("user.dir");
        String path = working+File.separator+"Projects"+File.separator+projectName+File.separator+"Reports"+File.separator+name;
        ArrayList<String> list = dosyaIceriginiOku(path);
        for(String item : list){
            txtArea.append(item+"\n");
            txtArea.setEditable(false);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        AssignmentList a1 = new AssignmentList();
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String name = (String)list.getSelectedValue();
        String working = System.getProperty("user.dir");
        String newName = FileWriterA.extensionOfFile(name);
        System.out.println(newName);
        System.out.println(assignmentName);
        String fullPath = working+File.separator+"Projects"+File.separator+projectName+File.separator+"Assignments"+File.separator+newName;
        try{
            FileWriterA.renameFile(fullPath+".c", newName+".txt");
            FileWriterA.renameFile(fullPath+".py", newName+".txt");
            FileWriterA.renameFile(fullPath+".java", newName+".txt");
            FileWriterA.renameFile(fullPath+".cpp", newName+".txt");
        }catch(Exception e){
            
        }
        String np = fullPath+".txt";
        ArrayList<String> list = dosyaIceriginiOku(np);
        txtArea.setText("");
        for(String item : list){
            txtArea.append(item+"\n");
            txtArea.setEditable(false);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    public static ArrayList<String> dosyaIceriginiOku(String dosyaYolu) {
        ArrayList<String> satirlar = new ArrayList<>();

        try {
            File dosya = new File(dosyaYolu);
            BufferedReader okuyucu = new BufferedReader(new FileReader(dosya));

            String satir;
            while ((satir = okuyucu.readLine()) != null) {
                satirlar.add(satir);
            }

            okuyucu.close();
        } catch (IOException e) {
            System.out.println("Dosya okuma hatası: " + e.getMessage());
        }

        return satirlar;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnalyseCodeAndOutput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnalyseCodeAndOutput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnalyseCodeAndOutput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnalyseCodeAndOutput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnalyseCodeAndOutput().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> list;
    private javax.swing.JTextArea txtArea;
    // End of variables declaration//GEN-END:variables
}
