/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject1;

import java.awt.event.ActionEvent;
import java.io.File;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Efe
 */
public class CreateAssignment extends javax.swing.JFrame {

    /**
     * Creates new form CreateAssignment
     */
    public CreateAssignment() {
        initComponents();
    }
    
    String output;

    Project p1 = new Project();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTitle = new javax.swing.JTextField();
        btnAddAssignment = new javax.swing.JButton();
        languageBox = new javax.swing.JComboBox<>();
        txtDescription = new javax.swing.JTextField();
        alertText = new javax.swing.JLabel();
        btnChooseFile = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtTitle.setText("Title of assignment");
        txtTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTitleActionPerformed(evt);
            }
        });

        btnAddAssignment.setText("Add Assignment");
        btnAddAssignment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAssignmentActionPerformed(evt);
            }
        });

        languageBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "C", "C++", "Java", "Python" }));
        languageBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                languageBoxActionPerformed(evt);
            }
        });

        txtDescription.setText("Description");
        txtDescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescriptionActionPerformed(evt);
            }
        });

        alertText.setText("-");

        btnChooseFile.setText("Choose file ");
        btnChooseFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChooseFileActionPerformed(evt);
            }
        });

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtTitle, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(languageBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtDescription, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(btnChooseFile)
                        .addGap(123, 123, 123)
                        .addComponent(alertText)))
                .addContainerGap(344, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(285, 285, 285)
                .addComponent(btnAddAssignment)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(76, 76, 76))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(languageBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnChooseFile, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alertText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddAssignment)
                    .addComponent(jButton1))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTitleActionPerformed

    private void txtDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescriptionActionPerformed

    private void btnAddAssignmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAssignmentActionPerformed
        if(output==null){
            JOptionPane.showMessageDialog(null, "You didnt choose any input file");
            return;
        }        
        p1.setDescb(txtDescription.getText());
        p1.setTitle(txtTitle.getText());
        p1.setLanguage((String) languageBox.getSelectedItem());

        FileWriterA.createProjectWithNotepad(txtTitle.getText());
        System.out.println(output);
        System.out.println(output+"*0***");
        MultiLanguagePathCompiler.compileAndRun(output,txtTitle.getText());
        FileWriterA.txtOverwrite("Output",txtTitle.getText());
        ArrayList<String> descbList = new ArrayList<>();
        ArrayList<String> langList = new ArrayList<>();
        descbList.add(txtDescription.getText());
        langList.add((String) languageBox.getSelectedItem());
        FileWriterA.txtOverwriteAlternative("Description",descbList,txtTitle.getText());
        FileWriterA.txtOverwriteAlternative("Language", langList,txtTitle.getText());
        this.setVisible(false);
        AssignmentList l1 = new AssignmentList();
        l1.setVisible(true);
        String myFileName = FileWriterA.lastOfFilePathWithExtension(output);
        String saltFileName = FileWriterA.extensionOfFile(output);
        String workingPath = System.getProperty("user.dir");
        String wholePath = workingPath+File.separator+"Projects"+File.separator+(String)txtTitle.getText()+File.separator+myFileName;
        System.out.println("Whole path:"+wholePath);
        String newName = "CodeFile.txt";
        String filePathForSource = wholePath;
        try{
            FileWriterA.renameFile(filePathForSource, newName);
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_btnAddAssignmentActionPerformed

    private void btnChooseFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseFileActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        int returnValue = fileChooser.showOpenDialog(this);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            System.out.println("Seçilen Dosya: " + fileChooser.getSelectedFile().getPath());
            output = fileChooser.getSelectedFile().getPath();
            String lastTwo = output.substring(output.length() - 2);
            if(lastTwo.equals(".c")){
                if(((String) languageBox.getSelectedItem()).equals("C")){
                    
                }else{
                    JOptionPane.showMessageDialog(null, "Please choose another file, extension of the file and language doesnt fit.");
                }
            }
            if(lastTwo.equals(".java")){
                if(((String) languageBox.getSelectedItem()).equals("Java")){
                    
                }else{
                    JOptionPane.showMessageDialog(null, "Please choose another file, extension of the file and language doesnt fit.");
                }
            }
            if(lastTwo.equals(".py")){
                if(((String) languageBox.getSelectedItem()).equals("Python")){
                    
                }else{
                    JOptionPane.showMessageDialog(null, "Please choose another file, extension of the file and language doesnt fit.");
                }
            }
            if(lastTwo.equals(".cpp")){
                if(((String) languageBox.getSelectedItem()).equals("C++")){
                    
                }else{
                    JOptionPane.showMessageDialog(null, "Please choose another file, extension of the file and language doesnt fit.");
                }
            }            
            
        } else {
            System.out.println("Dosya Seçme İptal Edildi");
        }
        
        
    }//GEN-LAST:event_btnChooseFileActionPerformed

    private void languageBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_languageBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_languageBoxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        AssignmentList l1 = new AssignmentList();
        l1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed
    private void btnFileChooserActionPerformed(ActionEvent evt) {
        JFileChooser fileChooser = new JFileChooser();
        int returnValue = fileChooser.showOpenDialog(this);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            System.out.println("Seçilen Dosya: " + fileChooser.getSelectedFile().getPath());
        } else {
            System.out.println("Dosya Seçme İptal Edildi");
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateAssignment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateAssignment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateAssignment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateAssignment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateAssignment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alertText;
    private javax.swing.JButton btnAddAssignment;
    private javax.swing.JButton btnChooseFile;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> languageBox;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtTitle;
    // End of variables declaration//GEN-END:variables
}
